;     תתתתתתתתשששששששש----======[Comment]=====------שששששששששתתתתתתתתת
;
;       UniversE Demo System 32 v0.6ב
;
;       bY BamboOS of UniversE 19.12.1999
;
;    תתתתתתתתשששששששש----======[EoComment]=====------שששששששששתתתתתתתתת
;      תתתתתתתתשששששששש----======[Macros]=====------שששששששששתתתתתתתתת

INCLUDE Mac32\text32.asm
INCLUDE Mac32\Main32.asm
INCLUDE Mac32\EVS.asm

;     תתתתתתתתשששששששש----======[EoMacros]=====------שששששששששתתתתתתתתת
